<a href="https://colab.research.google.com/github/fredyah/mytorchscript/blob/main/1_TorchDeepLearn_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np




In [3]:
## Numpy建立矩陣的方式：(float64)

np1 = np.random.rand(3, 4)
print(np1)
print(np1.dtype)

[[0.82677308 0.46461887 0.75772479 0.98488954]
 [0.80418327 0.07667379 0.57791227 0.80309005]
 [0.14310139 0.50871746 0.94553405 0.23703314]]
float64


In [4]:
## Torch 建立矩陣的方式：(預設為float32)

tensor_2d = torch.randn(3,4)
print(tensor_2d)
print(tensor_2d.dtype)

tensor_3d = torch.zeros(2, 3, 4)
print(tensor_3d)
print(tensor_3d.dtype)

tensor([[ 0.8431,  0.7698, -0.1355,  1.3530],
        [ 0.0046,  1.9851, -1.3188, -0.7744],
        [ 0.6285, -1.4919, -1.1204,  0.2293]])
torch.float32
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
torch.float32


In [5]:
## 將其他矩陣轉換成tensor矩陣

my_tensor = torch.tensor(np1)
print(my_tensor)
print(my_tensor.dtype)


tensor([[0.8268, 0.4646, 0.7577, 0.9849],
        [0.8042, 0.0767, 0.5779, 0.8031],
        [0.1431, 0.5087, 0.9455, 0.2370]], dtype=torch.float64)
torch.float64


In [6]:
## 生成一維張量的方式

my_torch = torch.arange(10)
print(my_torch)
print(my_torch.dtype)

my_torch = my_torch.reshape(2, 5)
print(my_torch)
print(my_torch.dtype)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.int64
tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
torch.int64


In [7]:
## 另一種reshape方式，可避免錯誤(使用-1，程式會自動判斷數量)

my_torch_2 = torch.arange(10)
my_torch_2 = my_torch.reshape(2, -1)
print(my_torch_2)
print(my_torch_2.dtype)


my_torch_3 = torch.arange(16)
my_torch_3 = my_torch_3.reshape(2, -1, 2)
print(my_torch_3)
print(my_torch_3.dtype)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
torch.int64
tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]]])
torch.int64


In [21]:
## View和reshape有點類似，用法如下：(使用view可以避免複製，更省內存，若是張量不連續，可加contiguous  --  .contiguous().view() )

my_torch_5 = torch.arange(10)
my_torch_5 = my_torch_5.view(2, 5)  ## my_torch_5.contiguous().view(2, 5)
print(my_torch_5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


In [22]:
print(my_torch_5[0, -2])

print(my_torch_5[0, 2])
my_torch_5[0, 2] = 1080
print(my_torch_5)

tensor(3)
tensor(2)
tensor([[   0,    1, 1080,    3,    4],
        [   5,    6,    7,    8,    9]])
