<a href="https://colab.research.google.com/github/fredyah/mytorchscript/blob/main/1_TorchDeepLearn_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import torch
import numpy as np




[[0.44017193 0.2896171  0.2781134  0.2108928 ]
 [0.70026434 0.32146555 0.59892098 0.42764737]
 [0.58467222 0.73937179 0.87984711 0.77971868]]
float64


In [5]:
## Numpy建立矩陣的方式：(float64)

np1 = np.random.rand(3, 4)
print(np1)
print(np1.dtype)

[[0.66322863 0.34725086 0.5027007  0.67676785]
 [0.32687253 0.47288306 0.17705763 0.79866202]
 [0.77053578 0.47992365 0.26414656 0.21817079]]
float64


In [8]:
## Torch 建立矩陣的方式：(預設為float32)

tensor_2d = torch.randn(3,4)
print(tensor_2d)
print(tensor_2d.dtype)

tensor_3d = torch.zeros(2, 3, 4)
print(tensor_3d)
print(tensor_3d.dtype)

tensor([[ 1.2086,  0.0422, -0.3631,  0.0054],
        [-1.3442, -1.2822,  0.2444, -0.3586],
        [ 0.5400,  1.0452, -0.3485, -0.0525]])
torch.float32
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
torch.float32


In [11]:
## 將其他矩陣轉換成tensor矩陣

my_tensor = torch.tensor(np1)
print(my_tensor)
print(my_tensor.dtype)


tensor([[0.6632, 0.3473, 0.5027, 0.6768],
        [0.3269, 0.4729, 0.1771, 0.7987],
        [0.7705, 0.4799, 0.2641, 0.2182]], dtype=torch.float64)
torch.float64
