<a href="https://colab.research.google.com/github/fredyah/mytorchscript/blob/main/1_TorchDeepLearn_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import numpy as np




In [4]:
## Numpy建立矩陣的方式：(float64)

np1 = np.random.rand(3, 4)
print(np1)
print(np1.dtype)

[[0.13754129 0.36274739 0.00127834 0.14970044]
 [0.96515875 0.63128582 0.7800275  0.89041331]
 [0.76484345 0.77622066 0.94434618 0.16834999]]
float64


In [5]:
## Torch 建立矩陣的方式：(預設為float32)

tensor_2d = torch.randn(3,4)
print(tensor_2d)
print(tensor_2d.dtype)

tensor_3d = torch.zeros(2, 3, 4)
print(tensor_3d)
print(tensor_3d.dtype)

tensor([[-0.2359,  1.4749, -1.2741,  0.7571],
        [-0.8932, -0.1832, -0.2064, -0.0042],
        [-0.4828, -0.3397,  1.9388, -0.8402]])
torch.float32
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
torch.float32


In [6]:
## 將其他矩陣轉換成tensor矩陣

my_tensor = torch.tensor(np1)
print(my_tensor)
print(my_tensor.dtype)


tensor([[0.1375, 0.3627, 0.0013, 0.1497],
        [0.9652, 0.6313, 0.7800, 0.8904],
        [0.7648, 0.7762, 0.9443, 0.1683]], dtype=torch.float64)
torch.float64


In [7]:
## 生成一維張量的方式

my_torch = torch.arange(10)
print(my_torch)
print(my_torch.dtype)

my_torch = my_torch.reshape(2, 5)
print(my_torch)
print(my_torch.dtype)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.int64
tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
torch.int64


In [8]:
## 另一種reshape方式，可避免錯誤(使用-1，程式會自動判斷數量)

my_torch_2 = torch.arange(10)
my_torch_2 = my_torch.reshape(2, -1)
print(my_torch_2)
print(my_torch_2.dtype)


my_torch_3 = torch.arange(16)
my_torch_3 = my_torch_3.reshape(2, -1, 2)
print(my_torch_3)
print(my_torch_3.dtype)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
torch.int64
tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]]])
torch.int64


In [9]:
## View和reshape有點類似，用法如下：(使用view可以避免複製，更省內存，若是張量不連續，可加contiguous  --  .contiguous().view() )

my_torch_5 = torch.arange(10)
my_torch_5 = my_torch_5.view(2, 5)  ## my_torch_5.contiguous().view(2, 5)
print(my_torch_5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


In [10]:
print(my_torch_5[0, -2])

print(my_torch_5[0, 2])
my_torch_5[0, 2] = 1080
print(my_torch_5)

tensor(3)
tensor(2)
tensor([[   0,    1, 1080,    3,    4],
        [   5,    6,    7,    8,    9]])


In [30]:
## 張量的四則運算：

tensor_a = torch.tensor([1, 2, 3, 4])
tensor_b = torch.tensor([5, 6, 7, 8])
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [29]:
## 張量相加--Addition ：( 可使用 + 號，或是 torch.add() 進行 )

tensor_c = tensor_a + tensor_b
tensor_d = torch.add(tensor_a, tensor_b)
print(tensor_c)
print(tensor_d)

tensor([11, 14, 17, 20])
tensor([11, 14, 17, 20])


In [13]:
## 張量相減--Subtraction ( 可使用 - 號，或是 torch.sub() 進行 )

tensor_e = tensor_b - tensor_a
tensor_f = torch.sub(tensor_b, tensor_a)
print(tensor_e)
print(tensor_f)

tensor([4, 4, 4, 4])
tensor([4, 4, 4, 4])


In [16]:
## 張量相乘--Multiplication  ( 可使用 * 號，或是 torch.mul() 進行 )

tensor_g = tensor_a * tensor_b
tensor_h = torch.mul(tensor_a, tensor_b)
print(tensor_g)
print(tensor_h)

tensor([ 5, 12, 21, 32])
tensor([ 5, 12, 21, 32])


In [21]:
## 張量相除--Division  ( 可使用 / 號，或是 torch.div() 進行 )

tensor_i = tensor_b / tensor_a
tensor_j = torch.div(tensor_b, tensor_a)
print(tensor_i)
print(tensor_j)

tensor([5.0000, 3.0000, 2.3333, 2.0000])
tensor([5.0000, 3.0000, 2.3333, 2.0000])


In [23]:
## 張量取餘數--RemainderModulus  ( 可使用 % 號，或是 torch.div() 進行 )

tensor_k = tensor_b % tensor_a
tensor_l = torch.remainder(tensor_b, tensor_a)
print(tensor_k)
print(tensor_l)

tensor([0, 0, 1, 0])
tensor([0, 0, 1, 0])


In [24]:
## 張量次方或指數--Exponents, Power

tensor_m = torch.pow(tensor_a , tensor_b)
print(tensor_m)


tensor([    1,    64,  2187, 65536])
tensor([1, 2, 3, 4])


In [33]:
## 張量四則運算的另一種表示方法，以加法為例：( 在運算function後面加一個底線 add_() ，即可重新分配值，也就表示值已經改變了 )

tensor_a.add(tensor_b)  ## tensor_a 未改變
print(tensor_a.add(tensor_b))
print(tensor_a)

tensor_a.add_(tensor_b)  ## tensor_a 已改變
print(tensor_a)

tensor([ 6,  8, 10, 12])
tensor([1, 2, 3, 4])
tensor([ 6,  8, 10, 12])
